[project]
name = "pre-existing-condition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=7.3.0",
    # https://plotly.com/python/static-image-export/#kaleido
    # fix for pandas.Timestamp is unreleased
    # https://github.com/plotly/Kaleido/pull/461
    "kaleido @ git+https://github.com/plotly/Kaleido.git#subdirectory=src/py",
    "nbformat>=4.2.0",
    "pandas",
    # wrds only supports Python 2.x
    "pandas-stubs==2.*",
    "plotly[express]>=6.8.0",
    "pytz>=2026.2",
    # https://github.com/wharton/wrds/issues/57
    "wrds>=3.3.0",
    "zstandard>=0.25.0",
]
